services:
  bot:
    container_name: astris
    image: fowl1029/astris:latest
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GROQ_API=${GROQ_API}
    volumes:
      - ./config.json:/app/config.json

  watchtower:
    container_name: astris-watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_USER=fowl1029
      - REPO_PASS=${REPO_PASS}
    command: --interval 60
    restart: always
